"""empty message

Revision ID: 69c73fba9f11
Revises: 73a2c21d5196
Create Date: 2024-01-18 21:24:58.410510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '69c73fba9f11'
down_revision: Union[str, None] = '73a2c21d5196'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('document_assistant_id_key', 'document', type_='unique')
    op.create_index(op.f('ix_document_assistant_id'), 'document', ['assistant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_assistant_id'), table_name='document')
    op.create_unique_constraint('document_assistant_id_key', 'document', ['assistant_id'])
    # ### end Alembic commands ###
